# These are supported funding model platforms

github: [Michael-Njoroge] 
patreon: Michael-Njoroge
open_collective: Michael-Njoroge
ko_fi: Michael-Njoroge
tidelift: npm/Michael-Njoroge
community_bridge: Michael-Njoroge
liberapay: Michael-Njoroge
issuehunt: Michael-Njoroge
lfx_crowdfunding: Michael-Njoroge
polar: Michael-Njoroge
buy_me_a_coffee: Michael-Njoroge
